services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chemga-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ~/ChemGaLogs:/app/Logs