// <auto-generated />
using System;
using ChemGa.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChemGa.Migrations
{
    [DbContext(typeof(AppDatabase))]
    [Migration("20250918111810_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChemGa.Database.Models.Giveaway", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("HostId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsEnded")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.PrimitiveCollection<decimal[]>("ParticipantIds")
                        .IsRequired()
                        .HasColumnType("numeric(20,0)[]");

                    b.Property<string>("Prize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<decimal[]>("RoleRequirements")
                        .IsRequired()
                        .HasColumnType("numeric(20,0)[]");

                    b.PrimitiveCollection<decimal[]>("RoleRestrictions")
                        .IsRequired()
                        .HasColumnType("numeric(20,0)[]");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WinnerCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<decimal[]>("WinnerIds")
                        .IsRequired()
                        .HasColumnType("numeric(20,0)[]");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("giveaway");
                });
#pragma warning restore 612, 618
        }
    }
}
